package com.ikea.crypto.server.service;

import com.ikea.crypto.common.AesCipherPayload;
import com.ikea.crypto.common.CryptoConstants;
import com.ikea.crypto.common.EncodingUtils;
import com.ikea.crypto.common.core.AesGcmCryptoService;
import com.ikea.crypto.common.core.CryptoSessionMaterialFactory;
import com.ikea.crypto.common.ecdh.*;
import com.ikea.crypto.server.context.CryptoSessionContextAccessor;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.util.StringUtils;

import javax.crypto.SecretKey;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.file.Path;
import java.security.*;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.time.Duration;
import java.util.Arrays;

/**
 * EcdhCryptoServer is responsible for handling ECDH key generation, encryption, and decryption on the server side.
 * It operates completely statelessly without Redis by encapsulating ephemeral private keys into encrypted AEAD tickets.
 */
@Slf4j
public class EcdhCryptoServer {

    public static final Duration DEFAULT_TICKET_TTL = Duration.ofMinutes(5);

    /*
     * The ECDSA private key is used to sign the ECDH ephemeral public keys generated by the server.
     */
    @Getter
    private final PrivateKey ecdsaPrivateKey;

    /*
     * The ECDSA public key is used for verifying the signatures of the ECDH ephemeral public keys.
     */
    private final PublicKey ecdsaPublicKey;

    /*
     * The master symmetric key used to encrypt and decrypt stateless ephemeral key tickets.
     */
    private final SecretKey ticketMasterKey;

    private final Duration ticketTtl;

    private final SecureRandom secureRandom;

    public EcdhCryptoServer(PrivateKey ecdsaPrivateKey, PublicKey ecdsaPublicKey, SecretKey ticketMasterKey) {
        this(ecdsaPrivateKey, ecdsaPublicKey, ticketMasterKey, DEFAULT_TICKET_TTL);
    }

    public EcdhCryptoServer(
            PrivateKey ecdsaPrivateKey,
            PublicKey ecdsaPublicKey,
            SecretKey ticketMasterKey,
            Duration ticketTtl
    ) {
        if (ecdsaPrivateKey == null || ecdsaPublicKey == null) {
            throw new IllegalArgumentException("ECDSA key pair is required.");
        }
        if (ticketMasterKey == null) {
            throw new IllegalArgumentException("Ticket master key is required for stateless ephemeral key encryption.");
        }
        if (ticketTtl == null || ticketTtl.isZero() || ticketTtl.isNegative()) {
            throw new IllegalArgumentException("Ticket TTL must be greater than zero.");
        }
        this.ecdsaPrivateKey = ecdsaPrivateKey;
        this.ecdsaPublicKey = ecdsaPublicKey;
        this.ticketMasterKey = ticketMasterKey;
        this.ticketTtl = ticketTtl;
        this.secureRandom = new SecureRandom();
    }

    /**
     * Creates an instance of EcdhCryptoServer, loading or generating the ECDSA key pair and ticket master key.
     *
     * @param keyDirectory The directory where server keys are stored or will be generated.
     * @return An instance of EcdhCryptoServer.
     */
    public static EcdhCryptoServer create(Path keyDirectory) throws GeneralSecurityException, IOException {
        log.info("Creating stateless EcdhCryptoServer from keyDirectory={}", keyDirectory);
        AbstractCryptoKeyService.ensureKeyDirectory(keyDirectory);
        KeyPair ecdsaKeyPair = AbstractCryptoKeyService.loadOrCreateLongLivedKeyPair(
                keyDirectory.resolve("ecdsa-private-key.pkcs8"),
                keyDirectory.resolve("ecdsa-public-key.x509"),
                KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC),
                generator -> generator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH))
        );
        SecretKey ticketMasterKey = AbstractCryptoKeyService.loadOrCreateMasterKey(
                keyDirectory.resolve("ecdh-ticket-master-key.aes")
        );
        return new EcdhCryptoServer(ecdsaKeyPair.getPrivate(), ecdsaKeyPair.getPublic(), ticketMasterKey);
    }

    /**
     * Returns the long-lived ECDSA verification public key used to validate ECDH ephemeral signatures.
     */
    public EcdsaVerificationKeyResponse getEcdsaPublicKey() {
        String keyId = "ecdsa-20261001";
        long expiresAt = System.currentTimeMillis() + 30 * 24 * 60 * 60 * 1000L;
        return new EcdsaVerificationKeyResponse(
                EncodingUtils.toBase64(ecdsaPublicKey.getEncoded()),
                keyId,
                expiresAt
        );
    }

    /**
     * Generates a new ECDH ephemeral key pair, encapsulates the private key into an encrypted ticket,
     * signs the public key with ECDSA, and returns the response.
     */
    public EcdhEphemeralKeyResponse getEphemeralPublicKey() throws GeneralSecurityException {
        KeyPair ephemeralKeyPair = EcdhKeyPairFactory.generateEphemeralKeyPair();
        byte[] ephemeralPublicKeyBytes = ephemeralKeyPair.getPublic().getEncoded();
        String ephemeralPublicKeyBase64 = EncodingUtils.toBase64(ephemeralPublicKeyBytes);

        String keyTicket = packEphemeralPrivateKeyToTicket(ephemeralKeyPair.getPrivate(), ticketTtl);

        Signature signature = Signature.getInstance(CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA);
        signature.initSign(ecdsaPrivateKey);
        signature.update(ephemeralPublicKeyBytes);
        byte[] signatureBytes = signature.sign();
        String signatureBase64 = EncodingUtils.toBase64(signatureBytes);

        return new EcdhEphemeralKeyResponse(
                ephemeralPublicKeyBase64,
                CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA,
                signatureBase64,
                keyTicket
        );
    }

    /**
     * Decrypts the given EcdhCipherPayload by unpacking the ephemeral private key from the ticket
     * and performing key agreement with the client's ephemeral public key.
     */
    public String decrypt(EcdhCipherPayload payload) throws GeneralSecurityException {
        log.debug("start to decrypt EcdhCipherPayload");
        validatePayload(payload);

        String keyTicket = payload.handshakeContext().keyTicket();
        PrivateKey serverPrivateKey = unpackEphemeralPrivateKeyFromTicket(keyTicket);

        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(payload.handshakeContext().clientEphemeralPublicKeyBase64()))
        );

        byte[] sharedSecret = EcdhKeyAgreementService.deriveSharedSecret(serverPrivateKey, clientEphemeralPublicKey);
        // Store the negotiated shared secret in the request-scoped context for reuse in response encryption
        CryptoSessionContextAccessor.setSharedSecret(sharedSecret);

        log.debug("Deriving request AES key from sharedSecret, iv and hkdfInfo");
        SecretKey requestKey = EcdhKeyAgreementService.deriveAesKey(
                sharedSecret,
                EncodingUtils.fromBase64(payload.aesCipherPayload().ivBase64()),
                CryptoConstants.HKDF_INFO_REQUEST_AES_KEY
        );

        return decryptWithAes(payload, requestKey);
    }

    public AesCipherPayload encryptWithEcdhHandshakeContext(String data, EcdhHandshakeContext ecdhHandshakeContext) throws GeneralSecurityException {
        log.debug("start to encrypt using EcdhHandshakeContext");
        byte[] sharedSecret = CryptoSessionContextAccessor.getSharedSecret();
        if (sharedSecret != null) {
            log.debug("Reusing resolved shared secret from context to derive isolated response AES key");
            byte[] iv = CryptoSessionMaterialFactory.generateIv(secureRandom);
            SecretKey responseKey = EcdhKeyAgreementService.deriveAesKey(
                    sharedSecret,
                    iv,
                    CryptoConstants.HKDF_INFO_RESPONSE_AES_KEY
            );
            String encryptedDataBase64 = AesGcmCryptoService.encryptAsBase64(data, responseKey, iv);
            return new AesCipherPayload(
                    EncodingUtils.toBase64(iv),
                    encryptedDataBase64
            );
        }
        return encryptUsingKeyTicket(data, ecdhHandshakeContext);
    }

    private AesCipherPayload encryptUsingKeyTicket(
            String data,
            EcdhHandshakeContext handshakeContext
    ) throws GeneralSecurityException {
        if (!StringUtils.hasLength(handshakeContext.clientEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Client ephemeral public key is required for response encryption");
        }
        PrivateKey serverPrivateKey = unpackEphemeralPrivateKeyFromTicket(handshakeContext.keyTicket());
        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(handshakeContext.clientEphemeralPublicKeyBase64()))
        );

        byte[] iv = CryptoSessionMaterialFactory.generateIv(secureRandom);
        SecretKey responseKey = EcdhKeyAgreementService.deriveAesKey(
                serverPrivateKey,
                clientEphemeralPublicKey,
                iv,
                CryptoConstants.HKDF_INFO_RESPONSE_AES_KEY
        );

        String encryptedDataBase64 = AesGcmCryptoService.encryptAsBase64(data, responseKey, iv);
        return new AesCipherPayload(
                EncodingUtils.toBase64(iv),
                encryptedDataBase64
        );
    }

    private String packEphemeralPrivateKeyToTicket(PrivateKey privateKey, Duration ttl) throws GeneralSecurityException {
        log.debug("Packing ephemeral private key into encrypted stateless ticket");
        byte[] privateKeyBytes = privateKey.getEncoded();
        long expiresAt = System.currentTimeMillis() + ttl.toMillis();

        ByteBuffer buffer = ByteBuffer.allocate(Long.BYTES + privateKeyBytes.length);
        buffer.putLong(expiresAt);
        buffer.put(privateKeyBytes);
        byte[] plaintext = buffer.array();

        byte[] iv = CryptoSessionMaterialFactory.generateIv(secureRandom);
        byte[] ciphertext = AesGcmCryptoService.encrypt(plaintext, ticketMasterKey, iv);

        byte[] combined = new byte[iv.length + ciphertext.length];
        System.arraycopy(iv, 0, combined, 0, iv.length);
        System.arraycopy(ciphertext, 0, combined, iv.length, ciphertext.length);

        return EncodingUtils.toBase64(combined);
    }

    private PrivateKey unpackEphemeralPrivateKeyFromTicket(String keyTicket) throws GeneralSecurityException {
        log.debug("Unpacking ephemeral private key from encrypted stateless ticket");
        if (!StringUtils.hasLength(keyTicket)) {
            throw new IllegalArgumentException("Key ticket is required for stateless ECDH decryption but was not provided.");
        }
        byte[] combined;
        try {
            combined = EncodingUtils.fromBase64(keyTicket);
        } catch (Exception e) {
            throw new IllegalArgumentException("Key ticket is not valid Base64", e);
        }
        if (combined.length < 12 + 16 + Long.BYTES) {
            throw new IllegalArgumentException("Invalid key ticket format");
        }
        byte[] iv = Arrays.copyOfRange(combined, 0, 12);
        byte[] ciphertext = Arrays.copyOfRange(combined, 12, combined.length);

        byte[] plaintext;
        try {
            plaintext = AesGcmCryptoService.decrypt(ciphertext, ticketMasterKey, iv);
        } catch (GeneralSecurityException e) {
            throw new GeneralSecurityException("Key ticket verification failed: invalid or tampered ticket", e);
        }

        ByteBuffer buffer = ByteBuffer.wrap(plaintext);
        long expiresAt = buffer.getLong();
        if (System.currentTimeMillis() > expiresAt) {
            throw new IllegalArgumentException("Ephemeral key ticket has expired");
        }

        byte[] privateKeyBytes = new byte[buffer.remaining()];
        buffer.get(privateKeyBytes);
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(privateKeyBytes);
        return KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePrivate(keySpec);
    }

    private void validatePayload(EcdhCipherPayload payload) {
        if (payload == null) {
            throw new IllegalArgumentException("Payload cannot be null");
        }
        if (payload.handshakeContext() == null) {
            throw new IllegalArgumentException("Handshake context cannot be null");
        }
        if (!StringUtils.hasLength(payload.handshakeContext().clientEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Client ephemeral public key is required for ECDH decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.handshakeContext().serverEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Server ephemeral public key is required for ECDH Ephemeral decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.handshakeContext().keyTicket())) {
            throw new IllegalArgumentException("Key ticket is required in handshake context for stateless ECDH decryption.");
        }
        if (payload.aesCipherPayload() == null) {
            throw new IllegalArgumentException("AES cipher payload cannot be null");
        }
        if (!StringUtils.hasLength(payload.aesCipherPayload().ivBase64())) {
            throw new IllegalArgumentException("IV is required but was not provided.");
        }
        if (!StringUtils.hasLength(payload.aesCipherPayload().encryptedDataBase64())) {
            throw new IllegalArgumentException("Encrypted data is required but was not provided.");
        }
    }

    private String decryptWithAes(EcdhCipherPayload payload, SecretKey sessionKey) throws GeneralSecurityException {
        return AesGcmCryptoService.decryptFromBase64(
                payload.aesCipherPayload().encryptedDataBase64(),
                sessionKey,
                payload.aesCipherPayload().ivBase64()
        );
    }
}
