package com.ikea.crypto.server.service;

import com.ikea.crypto.common.AesCipherPayload;
import com.ikea.crypto.common.CryptoConstants;
import com.ikea.crypto.common.EncodingUtils;
import com.ikea.crypto.common.core.AesGcmCryptoService;
import com.ikea.crypto.common.core.CryptoSessionMaterialFactory;
import com.ikea.crypto.common.ecdh.*;
import com.ikea.crypto.server.config.EcdhCryptoConfiguration;
import com.ikea.crypto.server.context.CryptoSessionContextAccessor;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.util.StringUtils;

import javax.crypto.SecretKey;
import java.io.IOException;
import java.nio.file.Path;
import java.security.*;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.time.Duration;

/**
 * EcdhCryptoServer is responsible for handling ECDH key generation, encryption, and decryption on the server side.
 * It manages ECDH ephemeral key pairs and uses an ECDSA key pair for signing and verifying ephemeral public keys.
 */
@Slf4j
public class EcdhCryptoServer {

    public static final Duration DEFAULT_EPHEMERAL_KEY_TTL = Duration.ofMinutes(5);

    public static final long DEFAULT_MAX_EPHEMERAL_KEYS = 10000L;

    private static final String EPHEMERAL_KEY_PREFIX = "ecdh:ephemeral:";

    /*
     * The ECDSA private key is used to sign the ECDH ephemeral public keys generated by the server.
     */
    @Getter
    private final PrivateKey ecdsaPrivateKey;

    /*
     * The ECDSA public key is used for verifying the signatures of the ECDH ephemeral public keys.
     */
    private final PublicKey ecdsaPublicKey;

    private final StringRedisTemplate redisTemplate;

    public EcdhCryptoServer(PrivateKey ecdsaPrivateKey, PublicKey ecdsaPublicKey, StringRedisTemplate redisTemplate) {
        this(ecdsaPrivateKey, ecdsaPublicKey, DEFAULT_EPHEMERAL_KEY_TTL, DEFAULT_MAX_EPHEMERAL_KEYS, redisTemplate);
    }

    public EcdhCryptoServer(
            PrivateKey ecdsaPrivateKey,
            PublicKey ecdsaPublicKey,
            Duration ephemeralKeyTtl,
            long maxEphemeralKeys,
            StringRedisTemplate redisTemplate
    ) {
        if (ephemeralKeyTtl == null || ephemeralKeyTtl.isZero() || ephemeralKeyTtl.isNegative()) {
            throw new IllegalArgumentException("Ephemeral key TTL must be greater than zero.");
        }
        if (maxEphemeralKeys <= 0) {
            throw new IllegalArgumentException("Maximum ephemeral key count must be greater than zero.");
        }
        if (redisTemplate == null) {
            throw new IllegalArgumentException("Redis template is required for ECDH ephemeral key storage.");
        }
        this.ecdsaPrivateKey = ecdsaPrivateKey;
        this.ecdsaPublicKey = ecdsaPublicKey;
        this.redisTemplate = redisTemplate;
    }

    /**
     * Creates an instance of EcdhCryptoServer, loading or generating the ECDSA key pair from the specified directory.
     *
     * @param keyDirectory The directory where the ECDSA keys are stored or will be generated.
     * @return An instance of EcdhCryptoServer with the loaded or generated ECDSA keys.
     * @throws GeneralSecurityException If there is a security exception during key generation or loading.
     * @throws IOException              If there is an I/O error while accessing the key files.
     */
    public static EcdhCryptoServer create(Path keyDirectory, StringRedisTemplate redisTemplate)
            throws GeneralSecurityException, IOException {
        log.info("Creating EcdhCryptoServer from keyDirectory={}", keyDirectory);
        AbstractCryptoKeyService.ensureKeyDirectory(keyDirectory);
        KeyPair ecdsaKeyPair = AbstractCryptoKeyService.loadOrCreateLongLivedKeyPair(
                keyDirectory.resolve("ecdsa-private-key.pkcs8"),
                keyDirectory.resolve("ecdsa-public-key.x509"),
                KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC),
                generator -> generator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH))
        );
        return new EcdhCryptoServer(ecdsaKeyPair.getPrivate(), ecdsaKeyPair.getPublic(), redisTemplate);
    }

    /**
     * Returns the long-lived ECDSA verification public key used to validate ECDH ephemeral signatures.
     */
    public EcdsaVerificationKeyResponse getEcdsaPublicKey() {
        String keyId = "ecdsa-20261001";
        // Set the expiration time to 30 days from now (in milliseconds)
        long expiresAt = System.currentTimeMillis() + 30 * 24 * 60 * 60 * 1000L;
        return new EcdsaVerificationKeyResponse(
                EncodingUtils.toBase64(ecdsaPublicKey.getEncoded()),
                keyId,
                expiresAt
        );
    }

    /**
     * Generates a new ECDH ephemeral key pair, signs the public key with the server's ECDSA private key,
     * and returns the short-lived ECDH public key response.
     */
    public EcdhEphemeralKeyResponse getEphemeralPublicKey() throws GeneralSecurityException {
        KeyPair ephemeralKeyPair = EcdhKeyPairFactory.generateEphemeralKeyPair();
        byte[] ephemeralPublicKeyBytes = ephemeralKeyPair.getPublic().getEncoded();
        String ephemeralPublicKeyBase64 = EncodingUtils.toBase64(ephemeralPublicKeyBytes);
        saveEphemeralPrivateKey(ephemeralPublicKeyBase64, ephemeralKeyPair.getPrivate());

        Signature signature = Signature.getInstance(CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA);
        signature.initSign(ecdsaPrivateKey);
        signature.update(ephemeralPublicKeyBytes);
        byte[] signatureBytes = signature.sign();
        String signatureBase64 = EncodingUtils.toBase64(signatureBytes);

        return new EcdhEphemeralKeyResponse(
                ephemeralPublicKeyBase64,
                CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA,
                signatureBase64
        );
    }

    /**
     * Decrypts the given EcdhCipherPayload using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @return The decrypted string.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    public String decrypt(EcdhCipherPayload payload) throws GeneralSecurityException {
        log.debug("start to decrypt EcdhCipherPayload");
        validatePayload(payload);
        String serverPublicKeyBase64 = payload.handshakeContext().serverEphemeralPublicKeyBase64();
        // Load the server's ephemeral private key corresponding to the provided server ephemeral public key
        PrivateKey serverPrivateKey = loadEphemeralPrivateKey(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException(
                    "No matching ephemeral server private key found for this ECDH request. " +
                            "Session key generation must use a fresh ephemeral key pair only."
            );
        }

        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(payload.handshakeContext().clientEphemeralPublicKeyBase64()))
        );

        log.debug("Deriving session key with serverPrivateKey(redis), clientEphemeralPublicKey, etc");
        SecretKey sessionKey = EcdhKeyAgreementService.deriveAesKey(
                serverPrivateKey,
                clientEphemeralPublicKey,
                EncodingUtils.fromBase64(payload.aesCipherPayload().ivBase64()),
                CryptoConstants.HKDF_INFO_REQUEST_AES_KEY
        );

        // Store the resolved session key in the request-scoped context for reuse in response encryption
        CryptoSessionContextAccessor.setResolvedSessionKey(sessionKey);

        String decryptedValue = decryptWithAes(payload, sessionKey);
        if (EcdhCryptoConfiguration.oneTimeUsedKey) {
            invalidateEphemeralPrivateKey(serverPublicKeyBase64);
        }
        return decryptedValue;
    }

    public AesCipherPayload encryptWithEcdhHandshakeContext(String data, EcdhHandshakeContext ecdhHandshakeContext) throws GeneralSecurityException {
        log.debug("start to encrypt using EcdhHandshakeContext");
        SecretKey sessionKey = CryptoSessionContextAccessor.getResolvedSessionKey();
        if (sessionKey != null) {
            log.debug("Reusing resolved session key from context for response encryption");
            byte[] iv = CryptoSessionMaterialFactory.generateIv(new SecureRandom());
            String encryptedDataBase64 = AesGcmCryptoService.encryptAsBase64(data, sessionKey, iv);
            return new AesCipherPayload(
                    EncodingUtils.toBase64(iv),
                    encryptedDataBase64
            );
        }
        return encryptWithServerPublicKeyAndClientPublicKey(
                data,
                ecdhHandshakeContext.serverEphemeralPublicKeyBase64(),
                ecdhHandshakeContext.clientEphemeralPublicKeyBase64()
        );
    }

    private AesCipherPayload encryptWithServerPublicKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64
    ) throws GeneralSecurityException {
        if (!StringUtils.hasLength(clientPublicKeyBase64)) {
            throw new IllegalArgumentException("Client ephemeral public key is required for response encryption");
        }
        if (!StringUtils.hasLength(serverPublicKeyBase64)) {
            throw new IllegalArgumentException("Server ephemeral public key is required for response encryption");
        }
        PrivateKey serverPrivateKey = loadEphemeralPrivateKey(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException("No matching ephemeral server private key found for response encryption");
        }
        return encryptWithServerPrivateKeyAndClientPublicKey(
                data,
                serverPublicKeyBase64,
                clientPublicKeyBase64,
                serverPrivateKey
        );
    }

    /**
     * Encrypts the given data using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param data                     The data to be encrypted.
     * @param serverPublicKeyBase64    The server's ephemeral public key in Base64 encoding.
     * @param clientPublicKeyBase64    The client's ephemeral public key in Base64 encoding.
     * @param serverPrivateKey         The server's ephemeral private key.
     * @return An EcdhCipherPayload containing the encrypted data and keys.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    private AesCipherPayload encryptWithServerPrivateKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64,
            PrivateKey serverPrivateKey
    ) throws GeneralSecurityException {
        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(clientPublicKeyBase64))
        );

        byte[] iv = CryptoSessionMaterialFactory.generateIv(new SecureRandom());

        log.debug("Deriving AES key from serverPrivateKey, clientEphemeralPublicKey, iv and hkdfInfo");
        SecretKey aesKey = EcdhKeyAgreementService.deriveAesKey(
                serverPrivateKey,
                clientEphemeralPublicKey,
                iv,
                CryptoConstants.HKDF_INFO_RESPONSE_AES_KEY
        );

        String encryptedDataBase64 = AesGcmCryptoService.encryptAsBase64(data, aesKey, iv);

        return new AesCipherPayload(
                EncodingUtils.toBase64(iv),
                encryptedDataBase64
        );
    }

    /**
     * Validates the provided AesCipherPayload to ensure that all required fields are present and not empty.
     *
     * @param payload The AesCipherPayload to validate.
     * @throws IllegalArgumentException If any required field is missing or empty.
     */
    private void validatePayload(EcdhCipherPayload payload) {
        if (payload == null) {
            throw new IllegalArgumentException("Payload cannot be null");
        }
        if (!StringUtils.hasLength(payload.handshakeContext().clientEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Client ephemeral public key is required for ECDH decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.handshakeContext().serverEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Server ephemeral public key is required for ECDH Ephemeral decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.aesCipherPayload().ivBase64())) {
            throw new IllegalArgumentException("IV is required but was not provided.");
        }
        if (!StringUtils.hasLength(payload.aesCipherPayload().encryptedDataBase64())) {
            throw new IllegalArgumentException("Encrypted data is required but was not provided.");
        }
    }

    /**
     * Decrypts the given EcdhCipherPayload using the provided AES key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @param sessionKey  The AES key to use for decryption.
     * @return The decrypted data as a String.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    private String decryptWithAes(EcdhCipherPayload payload, SecretKey sessionKey) throws GeneralSecurityException {
        return AesGcmCryptoService.decryptFromBase64(
                payload.aesCipherPayload().encryptedDataBase64(),
                sessionKey,
                payload.aesCipherPayload().ivBase64()
        );
    }

    private String redisKeyForEphemeralPrivateKey(String publicKeyBase64) {
        return EPHEMERAL_KEY_PREFIX + publicKeyBase64;
    }

    private void saveEphemeralPrivateKey(String publicKeyBase64, PrivateKey privateKey) {
        log.debug("Saving ECDH ephemeral key pair to Redis");
        String serializedKey = EncodingUtils.toBase64(privateKey.getEncoded());
        redisTemplate.opsForValue().set(redisKeyForEphemeralPrivateKey(publicKeyBase64), serializedKey, DEFAULT_EPHEMERAL_KEY_TTL);
    }

    /**
     * Loads the ephemeral private key corresponding to the given public key from Redis.
     *
     * @param publicKeyBase64 The Base64-encoded ephemeral public key.
     * @return The corresponding ephemeral private key, or null if not found.
     * @throws GeneralSecurityException If there is a security exception during key loading.
     */
    private PrivateKey loadEphemeralPrivateKey(String publicKeyBase64) throws GeneralSecurityException {
        log.debug("Loading ephemeral private key of specific public key from Redis");
        String serializedKey = redisTemplate.opsForValue().get(redisKeyForEphemeralPrivateKey(publicKeyBase64));
        if (serializedKey == null || serializedKey.isBlank()) {
            return null;
        }
        byte[] encodedPrivateKey = EncodingUtils.fromBase64(serializedKey);
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(encodedPrivateKey);
        return KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePrivate(keySpec);
    }

    private void invalidateEphemeralPrivateKey(String publicKeyBase64) {
        redisTemplate.delete(redisKeyForEphemeralPrivateKey(publicKeyBase64));
    }
}
