server:
  port: 9090

ecdh:
  crypto:
    key-directory: ${user.dir}/server/src/main/resources/keys

rsa:
  crypto:
    key-directory: ${user.dir}/server/src/main/resources/keys

logging:
  level:
    com.ikea.crypto: DEBUG
