server:
  port: 9090

spring:
  config:
    import:
      - optional:file:./.env[.properties]

sensitive:
  transport:
    crypto:
      kong-gateway-token: ${KONG_TO_ENCRYPTPII_AUTH_TOKEN:}

logging:
  level:
    com.ikea.crypto: DEBUG