package com.example.demo.server.crypto.ecdh;

import com.example.demo.crypto.CryptoConstants;
import com.example.demo.crypto.EncodingUtils;
import com.example.demo.crypto.core.AesGcmCryptoService;
import com.example.demo.crypto.ecdh.*;
import com.example.demo.server.crypto.AbstractCryptoKeyService;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.util.StringUtils;

import javax.crypto.SecretKey;
import java.io.IOException;
import java.nio.file.Path;
import java.security.*;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.time.Duration;

/**
 * EcdhCryptoServer is responsible for handling ECDH key generation, encryption, and decryption on the server side.
 * It manages ephemeral ECDH key pairs and uses an ECDSA key pair for signing and verifying ephemeral public keys.
 */
@Slf4j
public class EcdhCryptoServer {

    public static final Duration DEFAULT_EPHEMERAL_KEY_TTL = Duration.ofMinutes(5);

    public static final long DEFAULT_MAX_EPHEMERAL_KEYS = 10000L;

    private static final String EPHEMERAL_KEY_PREFIX = "ecdh:ephemeral:";

    /*
     * The ECDSA private key is used to sign the ephemeral ECDH public keys generated by the server.
     */
    @Getter
    private final PrivateKey ecdsaPrivateKey;

    /*
     * The ECDSA public key is used for verifying the signatures of the ephemeral ECDH public keys.
     */
    @Getter
    private final PublicKey ecdsaPublicKey;

    private final StringRedisTemplate redisTemplate;

    public EcdhCryptoServer(PrivateKey ecdsaPrivateKey, PublicKey ecdsaPublicKey, StringRedisTemplate redisTemplate) {
        this(ecdsaPrivateKey, ecdsaPublicKey, DEFAULT_EPHEMERAL_KEY_TTL, DEFAULT_MAX_EPHEMERAL_KEYS, redisTemplate);
    }

    public EcdhCryptoServer(
            PrivateKey ecdsaPrivateKey,
            PublicKey ecdsaPublicKey,
            Duration ephemeralKeyTtl,
            long maxEphemeralKeys,
            StringRedisTemplate redisTemplate
    ) {
        if (ephemeralKeyTtl == null || ephemeralKeyTtl.isZero() || ephemeralKeyTtl.isNegative()) {
            throw new IllegalArgumentException("Ephemeral key TTL must be greater than zero.");
        }
        if (maxEphemeralKeys <= 0) {
            throw new IllegalArgumentException("Maximum ephemeral key count must be greater than zero.");
        }
        if (redisTemplate == null) {
            throw new IllegalArgumentException("Redis template is required for distributed ECDH ephemeral key storage.");
        }
        this.ecdsaPrivateKey = ecdsaPrivateKey;
        this.ecdsaPublicKey = ecdsaPublicKey;
        this.redisTemplate = redisTemplate;
    }

    /**
     * Creates an instance of EcdhCryptoServer, loading or generating the ECDSA key pair from the specified directory.
     *
     * @param keyDirectory The directory where the ECDSA keys are stored or will be generated.
     * @return An instance of EcdhCryptoServer with the loaded or generated ECDSA keys.
     * @throws GeneralSecurityException If there is a security exception during key generation or loading.
     * @throws IOException              If there is an I/O error while accessing the key files.
     */
    public static EcdhCryptoServer create(Path keyDirectory, StringRedisTemplate redisTemplate)
            throws GeneralSecurityException, IOException {
        log.info("Creating EcdhCryptoServer from keyDirectory={}", keyDirectory);
        AbstractCryptoKeyService.ensureKeyDirectory(keyDirectory);
        KeyFactory ecdhKeyFactory = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC);
        KeyPair ecdsaKeyPair = AbstractCryptoKeyService.loadOrCreateKeyPair(
                keyDirectory.resolve("ecdsa-private-key.pkcs8"),
                keyDirectory.resolve("ecdsa-public-key.x509"),
                ecdhKeyFactory,
                generator -> generator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH))
        );
        return new EcdhCryptoServer(ecdsaKeyPair.getPrivate(), ecdsaKeyPair.getPublic(), redisTemplate);
    }

    /**
     * Generates a new ephemeral ECDH key pair, signs the public key with the server's ECDSA private key,
     * and returns an EcdhPublicKeyResponse containing the ephemeral public key, ECDSA public key, and signature.
     *
     * @return An EcdhPublicKeyResponse containing the ephemeral public key, ECDSA public key, and signature.
     * @throws GeneralSecurityException If there is a security exception during key generation or signing.
     */
    public EcdhPublicKeyResponse generateEphemeralEcdhPublicKey() throws GeneralSecurityException {
        KeyPair ephemeralKeyPair = EcdhKeyPairFactory.generateEphemeralKeyPair();
        byte[] ephemeralPublicKeyBytes = ephemeralKeyPair.getPublic().getEncoded();
        String ephemeralPublicKeyBase64 = EncodingUtils.toBase64(ephemeralPublicKeyBytes);
        saveEphemeralPrivateKey(ephemeralPublicKeyBase64, ephemeralKeyPair.getPrivate());

        byte[] ecdsaPublicKeyBytes = ecdsaPublicKey.getEncoded();
        String ecdsaPublicKeyBase64 = EncodingUtils.toBase64(ecdsaPublicKeyBytes);
        Signature signature = Signature.getInstance(CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA);
        signature.initSign(ecdsaPrivateKey);
        signature.update(ephemeralPublicKeyBytes);
        byte[] signatureBytes = signature.sign();
        String signatureBase64 = EncodingUtils.toBase64(signatureBytes);

        return new EcdhPublicKeyResponse(
                ephemeralPublicKeyBase64,
                ecdsaPublicKeyBase64,
                CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA,
                signatureBase64
        );
    }

    /**
     * Decrypts the given EcdhCipherPayload using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @return The decrypted string.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    public String decrypt(EcdhCipherPayload payload) throws GeneralSecurityException {
        log.info("start to decrypt EcdhCipherPayload");
        validatePayload(payload);
        String serverPublicKeyBase64 = payload.serverEphemeralPublicKeyBase64();
        PrivateKey serverPrivateKey = loadEphemeralPrivateKey(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException(
                    "No matching ephemeral server private key found for this ECDH request. " +
                            "Session key generation must use a fresh ephemeral key pair only."
            );
        }

        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(payload.clientEphemeralPublicKeyBase64()))
        );

        log.info("Deriving AES key from serverPrivateKey, clientEphemeralPublicKey, iv and hkdfInfo");
        SecretKey sessionKey = EcdhKeyAgreementService.deriveAesKey(
                serverPrivateKey,
                clientEphemeralPublicKey,
                EncodingUtils.fromBase64(payload.ivBase64()),
                CryptoConstants.HKDF_INFO_REQUEST_AES_KEY
        );

        String decryptedValue = decryptWithAes(payload, sessionKey);
        if (EcdhCryptoConfiguration.oneTimeUsedKey) {
            invalidateEphemeralPrivateKey(serverPublicKeyBase64);
        }
        return decryptedValue;
    }

    public EcdhCipherPayload encryptWithEcdhHandshakeContext(String data, EcdhHandshakeContext ecdhHandshakeContext) throws GeneralSecurityException {
        log.info("start to encrypt using EcdhHandshakeContext");
        return encryptWithServerPublicKeyAndClientPublicKey(
                data,
                ecdhHandshakeContext.serverEphemeralPublicKeyBase64(),
                ecdhHandshakeContext.clientEphemeralPublicKeyBase64()
        );
    }

    private EcdhCipherPayload encryptWithServerPublicKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64
    ) throws GeneralSecurityException {
        if (!StringUtils.hasLength(clientPublicKeyBase64)) {
            throw new IllegalArgumentException("Client ephemeral public key is required for response encryption");
        }
        if (!StringUtils.hasLength(serverPublicKeyBase64)) {
            throw new IllegalArgumentException("Server ephemeral public key is required for response encryption");
        }
        PrivateKey serverPrivateKey = loadEphemeralPrivateKey(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException("No matching ephemeral server private key found for response encryption");
        }
        return encryptWithServerPrivateKeyAndClientPublicKey(
                data,
                serverPublicKeyBase64,
                clientPublicKeyBase64,
                serverPrivateKey
        );
    }

    /**
     * Encrypts the given data using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param data                     The data to be encrypted.
     * @param serverPublicKeyBase64    The server's ephemeral public key in Base64 encoding.
     * @param clientPublicKeyBase64    The client's ephemeral public key in Base64 encoding.
     * @param serverPrivateKey         The server's ephemeral private key.
     * @return An EcdhCipherPayload containing the encrypted data and keys.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    private EcdhCipherPayload encryptWithServerPrivateKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64,
            PrivateKey serverPrivateKey
    ) throws GeneralSecurityException {
        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(clientPublicKeyBase64))
        );

        byte[] iv = new byte[CryptoConstants.GCM_IV_LENGTH_BYTES];
        new SecureRandom().nextBytes(iv);

        log.info("Deriving AES key from serverPrivateKey, clientEphemeralPublicKey, iv and hkdfInfo");
        SecretKey aesKey = EcdhKeyAgreementService.deriveAesKey(
                serverPrivateKey,
                clientEphemeralPublicKey,
                iv,
                CryptoConstants.HKDF_INFO_RESPONSE_AES_KEY
        );

        String encryptedDataBase64 = AesGcmCryptoService.encryptAsBase64(data, aesKey, iv);

        return new EcdhCipherPayload(
                clientPublicKeyBase64,
                serverPublicKeyBase64,
                EncodingUtils.toBase64(iv),
                encryptedDataBase64
        );
    }

    /**
     * Validates the provided EcdhCipherPayload to ensure that all required fields are present and not empty.
     *
     * @param payload The EcdhCipherPayload to validate.
     * @throws IllegalArgumentException If any required field is missing or empty.
     */
    private void validatePayload(EcdhCipherPayload payload) {
        if (payload == null) {
            throw new IllegalArgumentException("Payload cannot be null");
        }
        if (!StringUtils.hasLength(payload.clientEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Client ephemeral public key is required for ECDH decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.serverEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Server ephemeral public key is required for ECDH Ephemeral decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.ivBase64())) {
            throw new IllegalArgumentException("IV is required but was not provided.");
        }
        if (!StringUtils.hasLength(payload.encryptedDataBase64())) {
            throw new IllegalArgumentException("Encrypted data is required but was not provided.");
        }
    }

    /**
     * Decrypts the given EcdhCipherPayload using the provided AES key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @param sessionKey  The AES key to use for decryption.
     * @return The decrypted data as a String.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    private String decryptWithAes(EcdhCipherPayload payload, SecretKey sessionKey) throws GeneralSecurityException {
        return AesGcmCryptoService.decryptFromBase64(
                payload.encryptedDataBase64(),
                sessionKey,
                payload.ivBase64()
        );
    }

    private String redisKeyForEphemeralPrivateKey(String publicKeyBase64) {
        return EPHEMERAL_KEY_PREFIX + publicKeyBase64;
    }

    private void saveEphemeralPrivateKey(String publicKeyBase64, PrivateKey privateKey) {
        String serializedKey = EncodingUtils.toBase64(privateKey.getEncoded());
        redisTemplate.opsForValue().set(redisKeyForEphemeralPrivateKey(publicKeyBase64), serializedKey, DEFAULT_EPHEMERAL_KEY_TTL);
    }

    /**
     * Loads the ephemeral private key corresponding to the given public key from Redis.
     *
     * @param publicKeyBase64 The Base64-encoded ephemeral public key.
     * @return The corresponding ephemeral private key, or null if not found.
     * @throws GeneralSecurityException If there is a security exception during key loading.
     */
    private PrivateKey loadEphemeralPrivateKey(String publicKeyBase64) throws GeneralSecurityException {
        String serializedKey = redisTemplate.opsForValue().get(redisKeyForEphemeralPrivateKey(publicKeyBase64));
        if (serializedKey == null || serializedKey.isBlank()) {
            return null;
        }
        byte[] encodedPrivateKey = EncodingUtils.fromBase64(serializedKey);
        PKCS8EncodedKeySpec keySpec = new PKCS8EncodedKeySpec(encodedPrivateKey);
        return KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePrivate(keySpec);
    }

    private void invalidateEphemeralPrivateKey(String publicKeyBase64) {
        redisTemplate.delete(redisKeyForEphemeralPrivateKey(publicKeyBase64));
    }
}
