package com.example.demo.server.crypto.ecdh;

import com.example.demo.crypto.CryptoConstants;
import com.example.demo.crypto.EncodingUtils;
import com.example.demo.crypto.ecdh.EcdhCipherPayload;
import com.example.demo.crypto.ecdh.EcdhContext;
import com.example.demo.crypto.ecdh.EcdhPublicKeyResponse;
import com.example.demo.crypto.ecdh.HkdfUtils;
import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.springframework.util.StringUtils;

import javax.crypto.Cipher;
import javax.crypto.KeyAgreement;
import javax.crypto.SecretKey;
import javax.crypto.spec.GCMParameterSpec;
import javax.crypto.spec.SecretKeySpec;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.*;
import java.security.spec.ECGenParameterSpec;
import java.security.spec.PKCS8EncodedKeySpec;
import java.security.spec.X509EncodedKeySpec;
import java.time.Duration;

/**
 * EcdhCryptoServer is responsible for handling ECDH key generation, encryption, and decryption on the server side.
 * It manages ephemeral ECDH key pairs and uses an ECDSA key pair for signing and verifying ephemeral public keys.
 */
@Slf4j
public class EcdhCryptoServer {

    public static final Duration DEFAULT_EPHEMERAL_KEY_TTL = Duration.ofMinutes(5);

    public static final long DEFAULT_MAX_EPHEMERAL_KEYS = 10000L;

    /*
     * The ECDSA private key is used to sign the ephemeral ECDH public keys generated by the server.
     */
    @Getter
    private final PrivateKey ecdsaPrivateKey;

    /*
     * The ECDSA public key is used for verifying the signatures of the ephemeral ECDH public keys.
     */
    @Getter
    private final PublicKey ecdsaPublicKey;

    private final Cache<String, PrivateKey> ephemeralEcdhPrivateKeys;

    public EcdhCryptoServer(PrivateKey ecdsaPrivateKey, PublicKey ecdsaPublicKey) {
        this(ecdsaPrivateKey, ecdsaPublicKey, DEFAULT_EPHEMERAL_KEY_TTL, DEFAULT_MAX_EPHEMERAL_KEYS);
    }

    public EcdhCryptoServer(
            PrivateKey ecdsaPrivateKey,
            PublicKey ecdsaPublicKey,
            Duration ephemeralKeyTtl,
            long maxEphemeralKeys
    ) {
        if (ephemeralKeyTtl == null || ephemeralKeyTtl.isZero() || ephemeralKeyTtl.isNegative()) {
            throw new IllegalArgumentException("Ephemeral key TTL must be greater than zero.");
        }
        if (maxEphemeralKeys <= 0) {
            throw new IllegalArgumentException("Maximum ephemeral key count must be greater than zero.");
        }
        this.ecdsaPrivateKey = ecdsaPrivateKey;
        this.ecdsaPublicKey = ecdsaPublicKey;
        this.ephemeralEcdhPrivateKeys = Caffeine.newBuilder()
                .expireAfterWrite(ephemeralKeyTtl)
                .maximumSize(maxEphemeralKeys)
                .build();
    }

    /**
     * Creates an instance of EcdhCryptoServer, loading or generating the ECDSA key pair from the specified directory.
     *
     * @param keyDirectory The directory where the ECDSA keys are stored or will be generated.
     * @return An instance of EcdhCryptoServer with the loaded or generated ECDSA keys.
     * @throws GeneralSecurityException If there is a security exception during key generation or loading.
     * @throws IOException              If there is an I/O error while accessing the key files.
     */
    public static EcdhCryptoServer create(Path keyDirectory) throws GeneralSecurityException, IOException {
        log.info("Creating EcdhCryptoServer from keyDirectory={}", keyDirectory);
        Files.createDirectories(keyDirectory);
        KeyFactory ecdhKeyFactory = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC);
        KeyPair ecdsaKeyPair = loadOrCreateKeyPair(
                keyDirectory.resolve("ecdsa-private-key.pkcs8"),
                keyDirectory.resolve("ecdsa-public-key.x509"),
                ecdhKeyFactory
        );
        return new EcdhCryptoServer(ecdsaKeyPair.getPrivate(), ecdsaKeyPair.getPublic());
    }

    /**
     * Loads an existing ECDSA key pair from the specified files or generates a new one if the files do not exist.
     *
     * @param privateKeyPath The path to the private key file.
     * @param publicKeyPath  The path to the public key file.
     * @param keyFactory     The KeyFactory instance for generating keys.
     * @return A KeyPair containing the loaded or generated keys.
     * @throws GeneralSecurityException If there is a security exception during key generation or loading.
     * @throws IOException              If there is an I/O error while accessing the key files.
     */
    private static KeyPair loadOrCreateKeyPair(Path privateKeyPath, Path publicKeyPath, KeyFactory keyFactory)
            throws GeneralSecurityException, IOException {
        if (Files.exists(privateKeyPath) && Files.exists(publicKeyPath)) {
            PrivateKey privateKey = keyFactory.generatePrivate(new PKCS8EncodedKeySpec(Files.readAllBytes(privateKeyPath)));
            PublicKey publicKey = keyFactory.generatePublic(new X509EncodedKeySpec(Files.readAllBytes(publicKeyPath)));
            return new KeyPair(publicKey, privateKey);
        }

        KeyPairGenerator generator = KeyPairGenerator.getInstance(CryptoConstants.ALGORITHM_EC);
        generator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH));
        KeyPair keyPair = generator.generateKeyPair();
        Files.write(privateKeyPath, keyPair.getPrivate().getEncoded());
        Files.write(publicKeyPath, keyPair.getPublic().getEncoded());
        return keyPair;
    }

    /**
     * Generates a new ephemeral ECDH key pair, signs the public key with the server's ECDSA private key,
     * and returns an EcdhPublicKeyResponse containing the ephemeral public key, ECDSA public key, and signature.
     *
     * @return An EcdhPublicKeyResponse containing the ephemeral public key, ECDSA public key, and signature.
     * @throws GeneralSecurityException If there is a security exception during key generation or signing.
     */
    public EcdhPublicKeyResponse generateEphemeralEcdhPublicKey() throws GeneralSecurityException {
        log.info("Generating ephemeral public key");
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance(CryptoConstants.ALGORITHM_EC);
        keyPairGenerator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH));
        KeyPair ephemeralKeyPair = keyPairGenerator.generateKeyPair();
        byte[] ephemeralPublicKeyBytes = ephemeralKeyPair.getPublic().getEncoded();
        String ephemeralPublicKeyBase64 = EncodingUtils.toBase64(ephemeralPublicKeyBytes);
        ephemeralEcdhPrivateKeys.put(ephemeralPublicKeyBase64, ephemeralKeyPair.getPrivate());

        byte[] ecdsaPublicKeyBytes = ecdsaPublicKey.getEncoded();
        String ecdsaPublicKeyBase64 = EncodingUtils.toBase64(ecdsaPublicKeyBytes);
        Signature signature = Signature.getInstance(CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA);
        signature.initSign(ecdsaPrivateKey);
        signature.update(ephemeralPublicKeyBytes);
        byte[] signatureBytes = signature.sign();
        String signatureBase64 = EncodingUtils.toBase64(signatureBytes);

        return new EcdhPublicKeyResponse(
                ephemeralPublicKeyBase64,
                ecdsaPublicKeyBase64,
                CryptoConstants.SIGNATURE_ALGORITHM_SHA256_WITH_ECDSA,
                signatureBase64
        );
    }

    /**
     * Decrypts the given EcdhCipherPayload using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @return The decrypted string.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    public String decrypt(EcdhCipherPayload payload) throws GeneralSecurityException {
        log.info("EcdhCryptoServer decrypt {}", payload);
        validatePayload(payload);
        String serverPublicKeyBase64 = payload.serverEphemeralPublicKeyBase64();
        PrivateKey serverPrivateKey = ephemeralEcdhPrivateKeys.getIfPresent(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException(
                    "No matching ephemeral server private key found for this ECDH request. " +
                            "Session key generation must use a fresh ephemeral key pair only."
            );
        }

        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(payload.clientEphemeralPublicKeyBase64()))
        );
        KeyAgreement keyAgreement = KeyAgreement.getInstance(CryptoConstants.ALGORITHM_ECDH);
        keyAgreement.init(serverPrivateKey);
        keyAgreement.doPhase(clientEphemeralPublicKey, true);
        byte[] sharedSecret = keyAgreement.generateSecret();

        byte[] derivedAesKey = HkdfUtils.deriveAesKey(
                sharedSecret,
                EncodingUtils.fromBase64(payload.ivBase64()),
                CryptoConstants.HKDF_INFO_REQUEST_AES_KEY.getBytes(StandardCharsets.UTF_8),
                CryptoConstants.AES_KEY_SIZE_BITS / Byte.SIZE
        );

        SecretKey sessionKey = new SecretKeySpec(derivedAesKey, CryptoConstants.ALGORITHM_AES);
        String decryptedValue = decryptWithAes(payload, sessionKey);
        if (EcdhCryptoConfiguration.oneTimeUsedKey) {
            ephemeralEcdhPrivateKeys.invalidate(serverPublicKeyBase64);
        }
        return decryptedValue;
    }

    /**
     * Encrypts the given data using a newly generated ephemeral ECDH key pair and the server's ephemeral public key.
     *
     * @param data The data to be encrypted.
     * @return An EcdhCipherPayload containing the encrypted data and keys.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    public EcdhCipherPayload encrypt(String data) throws GeneralSecurityException {
        log.info("EcdhCryptoServer encrypt data={}", data);
        EcdhPublicKeyResponse publicKeyResponse = generateEphemeralEcdhPublicKey();
        return encryptWithServerPublicKey(data, publicKeyResponse.ephemeralPublicKeyBase64());
    }

    public EcdhCipherPayload encryptWithEcdhContext(String data, EcdhContext ecdhContext) throws GeneralSecurityException {
        return encryptWithServerPublicKeyAndClientPublicKey(data, ecdhContext.serverEphemeralPublicKeyBase64(), ecdhContext.clientEphemeralPublicKeyBase64());
    }

    private EcdhCipherPayload encryptWithServerPublicKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64
    ) throws GeneralSecurityException {
        log.info("EcdhCryptoServer encryptWithServerPublicKeyAndClientPublicKey data={}, serverPublicKeyBase64={}, clientPublicKeyBase64={}", data, serverPublicKeyBase64, clientPublicKeyBase64);
        if (!StringUtils.hasLength(clientPublicKeyBase64)) {
            throw new IllegalArgumentException("Client ephemeral public key is required for response encryption");
        }
        if (!StringUtils.hasLength(serverPublicKeyBase64)) {
            throw new IllegalArgumentException("Server ephemeral public key is required for response encryption");
        }
        // Retrieve the server's ephemeral private key corresponding to the provided server public key
        PrivateKey serverPrivateKey = ephemeralEcdhPrivateKeys.getIfPresent(serverPublicKeyBase64);
        if (serverPrivateKey == null) {
            throw new IllegalArgumentException("No matching ephemeral server private key found for response encryption");
        }
        return encryptWithServerPrivateKeyAndClientPublicKey(
                data,
                serverPublicKeyBase64,
                clientPublicKeyBase64,
                serverPrivateKey
        );
    }

    /**
     * Encrypts the given data using the provided server's ephemeral public key and a newly generated client's ephemeral key pair.
     *
     * @param data                     The data to be encrypted.
     * @param serverPublicKeyBase64    The server's ephemeral public key in Base64 encoding.
     * @return An EcdhCipherPayload containing the encrypted data and keys.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    private EcdhCipherPayload encryptWithServerPublicKey(String data, String serverPublicKeyBase64) throws GeneralSecurityException {
        log.info("EcdhCryptoServer encryptWithServerPublicKey data={}, serverPublicKeyBase64={}", data, serverPublicKeyBase64);
        KeyPairGenerator keyPairGenerator = KeyPairGenerator.getInstance(CryptoConstants.ALGORITHM_EC);
        keyPairGenerator.initialize(new ECGenParameterSpec(CryptoConstants.CURVE_ECDH));
        KeyPair clientEphemeralKeyPair = keyPairGenerator.generateKeyPair();

        PublicKey serverPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(serverPublicKeyBase64))
        );
        KeyAgreement keyAgreement = KeyAgreement.getInstance(CryptoConstants.ALGORITHM_ECDH);
        keyAgreement.init(clientEphemeralKeyPair.getPrivate());
        keyAgreement.doPhase(serverPublicKey, true);
        byte[] sharedSecret = keyAgreement.generateSecret();

        byte[] iv = new byte[CryptoConstants.GCM_IV_LENGTH_BYTES];
        new SecureRandom().nextBytes(iv);
        byte[] derivedAesKey = HkdfUtils.deriveAesKey(
                sharedSecret,
                iv,
                CryptoConstants.HKDF_INFO_REQUEST_AES_KEY.getBytes(StandardCharsets.UTF_8),
                CryptoConstants.AES_KEY_SIZE_BITS / Byte.SIZE
        );
        SecretKey aesKey = new SecretKeySpec(derivedAesKey, CryptoConstants.ALGORITHM_AES);
        byte[] encryptedData = encryptWithAes(data, aesKey, iv);

        return new EcdhCipherPayload(
                EncodingUtils.toBase64(clientEphemeralKeyPair.getPublic().getEncoded()),
                serverPublicKeyBase64,
                EncodingUtils.toBase64(iv),
                EncodingUtils.toBase64(encryptedData)
        );
    }

    /**
     * Encrypts the given data using the server's ephemeral private key and the client's ephemeral public key.
     *
     * @param data                     The data to be encrypted.
     * @param serverPublicKeyBase64    The server's ephemeral public key in Base64 encoding.
     * @param clientPublicKeyBase64    The client's ephemeral public key in Base64 encoding.
     * @param serverPrivateKey         The server's ephemeral private key.
     * @return An EcdhCipherPayload containing the encrypted data and keys.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    private EcdhCipherPayload encryptWithServerPrivateKeyAndClientPublicKey(
            String data,
            String serverPublicKeyBase64,
            String clientPublicKeyBase64,
            PrivateKey serverPrivateKey
    ) throws GeneralSecurityException {
        log.info("EcdhCryptoServer encryptWithServerPrivateKeyAndClientPublicKey data={}, serverPublicKeyBase64={}, clientPublicKeyBase64={}", data, serverPublicKeyBase64, clientPublicKeyBase64);
        PublicKey clientEphemeralPublicKey = KeyFactory.getInstance(CryptoConstants.ALGORITHM_EC).generatePublic(
                new X509EncodedKeySpec(EncodingUtils.fromBase64(clientPublicKeyBase64))
        );
        KeyAgreement keyAgreement = KeyAgreement.getInstance(CryptoConstants.ALGORITHM_ECDH);
        keyAgreement.init(serverPrivateKey);
        keyAgreement.doPhase(clientEphemeralPublicKey, true);
        byte[] sharedSecret = keyAgreement.generateSecret();

        byte[] iv = new byte[CryptoConstants.GCM_IV_LENGTH_BYTES];
        new SecureRandom().nextBytes(iv);
        byte[] derivedAesKey = HkdfUtils.deriveAesKey(
                sharedSecret,
                iv,
                CryptoConstants.HKDF_INFO_RESPONSE_AES_KEY.getBytes(StandardCharsets.UTF_8),
                CryptoConstants.AES_KEY_SIZE_BITS / Byte.SIZE
        );
        SecretKey aesKey = new SecretKeySpec(derivedAesKey, CryptoConstants.ALGORITHM_AES);
        byte[] encryptedData = encryptWithAes(data, aesKey, iv);

        return new EcdhCipherPayload(
                clientPublicKeyBase64,
                serverPublicKeyBase64,
                EncodingUtils.toBase64(iv),
                EncodingUtils.toBase64(encryptedData)
        );
    }

    /**
     * Validates the provided EcdhCipherPayload to ensure that all required fields are present and not empty.
     *
     * @param payload The EcdhCipherPayload to validate.
     * @throws IllegalArgumentException If any required field is missing or empty.
     */
    private void validatePayload(EcdhCipherPayload payload) {
        if (payload == null) {
            throw new IllegalArgumentException("Payload cannot be null");
        }
        if (!StringUtils.hasLength(payload.clientEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Client ephemeral public key is required for ECDH decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.serverEphemeralPublicKeyBase64())) {
            throw new IllegalArgumentException("Server ephemeral public key is required for ECDH Ephemeral decryption but was not provided.");
        }
        if (!StringUtils.hasLength(payload.ivBase64())) {
            throw new IllegalArgumentException("IV is required but was not provided.");
        }
        if (!StringUtils.hasLength(payload.encryptedDataBase64())) {
            throw new IllegalArgumentException("Encrypted data is required but was not provided.");
        }
    }

    /**
     * Decrypts the given EcdhCipherPayload using the provided AES key.
     *
     * @param payload The EcdhCipherPayload containing the encrypted data and keys.
     * @param sessionKey  The AES key to use for decryption.
     * @return The decrypted data as a String.
     * @throws GeneralSecurityException If there is a security exception during decryption.
     */
    private String decryptWithAes(EcdhCipherPayload payload, SecretKey sessionKey) throws GeneralSecurityException {
        log.info("EcdhCryptoServer decryptWithAes payload={}, sessionKey={}", payload, sessionKey);
        Cipher aesCipher = Cipher.getInstance(CryptoConstants.TRANSFORMATION_AES);
        aesCipher.init(
                Cipher.DECRYPT_MODE,
                sessionKey,
                new GCMParameterSpec(CryptoConstants.GCM_TAG_LENGTH_BITS, EncodingUtils.fromBase64(payload.ivBase64()))
        );
        byte[] plainBytes = aesCipher.doFinal(EncodingUtils.fromBase64(payload.encryptedDataBase64()));
        return new String(plainBytes, StandardCharsets.UTF_8);
    }

    /**
     * Encrypts the given data using AES encryption with the provided AES key and IV.
     *
     * @param data   The data to be encrypted.
     * @param aesKey The AES key to use for encryption.
     * @param iv     The initialization vector (IV) to use for encryption.
     * @return The encrypted data as a byte array.
     * @throws GeneralSecurityException If there is a security exception during encryption.
     */
    private byte[] encryptWithAes(String data, SecretKey aesKey, byte[] iv) throws GeneralSecurityException {
        log.info("EcdhCryptoServer encryptWithAes data={}, aesKey={}, iv={}", data, aesKey, iv);
        Cipher aesCipher = Cipher.getInstance(CryptoConstants.TRANSFORMATION_AES);
        aesCipher.init(Cipher.ENCRYPT_MODE, aesKey, new GCMParameterSpec(CryptoConstants.GCM_TAG_LENGTH_BITS, iv));
        return aesCipher.doFinal(data.getBytes(StandardCharsets.UTF_8));
    }
}
