server:
  port: 8080

crypto:
  server:
#    base-url: https://encryptpii-kong.kong.svc.cluster.local:8443  #run in k8s
    base-url: https://local.kong.test:18443 #run locally, need to trust kong or mitmproxy certificates
    endpoints:
      public-key: /crypto/server/public-key
      bidirectional: /crypto/server/bidirectional
      request-only: /crypto/server/request-only
      response-only: /crypto/server/response-only

plain:
  server:
    base-url: ${crypto.server.base-url}
    endpoints:
      normal: /plain/server/normal

logging:
  level:
    com.ikea.crypto: DEBUG