server:
  port: 8080
crypto:
  server:
    base-url: http://localhost:9090
    endpoints:
      rsa:
        public-key: /crypto/server/public-key
        bidirectional: /crypto/server/bidirectional
        request-only: /crypto/server/request-only
        response-only: /crypto/server/response-only

logging:
  level:
    com.ikea.crypto: DEBUG